on:
  push:
    tags:
      - "v[0-9]*"
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: yarn install --immutable --immutable-cache --check-cache

      - name: Build Extension
        run: yarn vsix

      - name: Upload extension to Actions Artifact
        uses: actions/upload-artifact@v3
        with:
          name: shiny-vscode
          path: "shiny*.vsix"

      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        if: ${{
          (github.event_name == 'push' &&
          github.repository_owner == 'posit-dev') ||
          github.event.pull_request.head.repo.fork == false
          }}
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          dryRun: ${{ !(github.event_name == 'push' && github.ref_type == 'tag') }}

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        if: ${{
          (github.event_name == 'push' &&
          github.repository_owner == 'posit-dev') ||
          github.event.pull_request.head.repo.fork == false
          }}
        with:
          pat: ${{ secrets.VSCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          dryRun: ${{ !(github.event_name == 'push' && github.ref_type == 'tag') }}
